# Generated by Django 2.0.1 on 2018-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.DateField()),
                ('bing_url', models.CharField(max_length=10000)),
                ('qiniu_url', models.CharField(max_length=10000)),
                ('image_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
